Feature/portal optimize
Ferlab-Ste-Justine/cqdg-portal-ui pull request #142
Opened 2023-09-25 20:38 UTC by ihannache

# FIX | FEAT | REFACTOR | PERF | DOCS : TITLE

- closes #TICKET_NUMBER

## Description

[JIRA LINK]

Acceptance Criterias

## Validation

- [ ] Code Approved
- [ ] QA Done
- [ ] Design/UI Approved from design

## Screenshot
### Before

### After

## QA

Steps to validate
Url (storybook, ...)
...

## Mention

@kstonge @luclemo

2023-09-25 22:49 UTC, atoulous commented on src/global.d.ts
> +declare global {
ce fichier peut etre mis dans `src/helpers` ?

2023-09-26 15:23 UTC, sebastienbonami requested changes

2023-09-26 15:23 UTC, sebastienbonami commented on package.json
> +    "@babel/plugin-proposal-private-property-in-object": "^7.14.5"
This package has been deprecated, you should replace it by `@babel/plugin-transform-private-property-in-object`.

2023-09-26 15:28 UTC, sebastienbonami commented
It's not that important, but the main comment of this PR should be edited has it's still a template.

2023-09-26 15:31 UTC, sebastienbonami commented
The check "Quality / Install Dependencies" fails because `package.json` and `package-lock.json` are not synced anymore. To fix.

2023-09-27 13:40 UTC, atoulous commented on entrypoint.sh
> +#!/bin/sh
Pour éviter de re-lister les variables ici j'ai réfléchi à importer les variables du file EnvVariables.ts, mais sans succes. Si tu as une idée..

2023-11-28 16:38 UTC, closed without merging