fix: CQDG-405 update study entity navigation locale
Ferlab-Ste-Justine/cqdg-portal-ui pull request #155
Opened 2023-10-10 19:53 UTC by francisl

# FIX | Navigation string for files

- closes https://ferlab-crsj.atlassian.net/browse/CQDG-405

## Description

Update `File` to match 'Data Files'

Acceptance Criterias

## Validation

- [ ] Code Approved
- [ ] QA Done

## Screensho

### After
![image](https://github.com/Ferlab-Ste-Justine/cqdg-portal-ui/assets/98903/cd91e35c-ad57-4451-963b-5e4c9d5ac0eb)

2023-10-10 20:10 UTC, atoulous commented on src/locales/en.ts
> +      file: 'Data Files',
Mb je me suis trompé ici.
Il faut supprimer cette ligne `file: 'File',` dans `entities.study`. La trad est dans `entities.file`
et utiliser `entities.file.datafile` au lieu de `entities.study.file`

2023-10-10 20:43 UTC, atoulous requested changes

2023-10-10 20:43 UTC, atoulous commented on src/views/StudyEntity/index.tsx
> +        title: intl.get('entities.study.data_files'),
`'entities.file.datafile'` (sans s a datafile car ils veulent au singulier)

2023-10-10 20:43 UTC, atoulous commented on src/locales/en.ts
> +      data_files: 'Data Files',
tu peux supprimer cette ligne, et celle `file: 'File',` dans fr.ts

2023-10-11 11:17 UTC, francisl commented on src/views/StudyEntity/index.tsx
> +        title: intl.get('entities.study.data_files'),
done

2023-10-11 11:17 UTC, francisl commented on src/locales/en.ts
> +      data_files: 'Data Files',
done

2023-10-11 12:39 UTC, atoulous approved these changes

2023-10-12 13:10 UTC, merged