feat: CQDG-299 edits on variant entity
Ferlab-Ste-Justine/cqdg-portal-ui pull request #158
Opened 2023-10-16 22:39 UTC by atoulous

# feat: CQDG-299 edits on variant entity
- closes #TICKET_NUMBER

## Description

https://ferlab-crsj.atlassian.net/browse/CQDG-135

Acceptance Criterias

## Validation

- [ ] Code Approved
- [ ] QA Done
- [ ] Design/UI Approved from design

## Screenshot
### Before

### After

## QA

Steps to validate
Url (storybook, ...)
...

## Mention

2023-10-17 10:11 UTC, kstonge commented
Modifier le titre de la PR

2023-10-17 14:04 UTC, AltefrohneGaelle commented on src/locales/fr.ts
> -        CQDGStudies: 'Études du CQDG',
Dans frequencies dans le fichier anglais tu as ajouté `subTitle: 'CQDG Studies',` je ne le vois pas dans le français.

2023-10-17 14:04 UTC, AltefrohneGaelle commented on src/views/VariantEntity/utils/frequencies.tsx
> +      value: '',
c'est voulu cette colonne vide ?

2023-10-17 14:12 UTC, atoulous commented on src/views/VariantEntity/utils/frequencies.tsx
> +      value: '',
Oui c'est pour avoir cette case vide

<img width="1622" alt="image" src="https://github.com/Ferlab-Ste-Justine/cqdg-portal-ui/assets/15524246/43e21914-99f0-4db6-b9ab-6a432e895ff6">

2023-10-17 14:12 UTC, atoulous commented on src/locales/fr.ts
> -        CQDGStudies: 'Études du CQDG',
c'etait un oublie `subTitle` j'ai fais avec CQDGStudies dans study

2023-10-17 14:17 UTC, AltefrohneGaelle commented on src/views/VariantEntity/utils/frequencies.tsx
> +      value: '',
est ce que tu ne veux pas un tiret aussi pour le total s'il n'y a pas de valeur ?

2023-10-17 14:22 UTC, atoulous commented on src/views/VariantEntity/utils/frequencies.tsx
> +      value: '',
Ce n'est pas demandé
`-` est utilisé pour une valeur manquante mais ici on n'attend pas de valeur. On ne peut pas faire de total de domain.

2023-10-17 14:33 UTC, AltefrohneGaelle approved these changes

2023-10-17 19:10 UTC, francisl approved these changes

2023-10-20 15:43 UTC, adipaul1981 approved these changes

2023-10-26 17:41 UTC, francisl requested changes

2023-10-26 17:41 UTC, francisl commented on src/views/VariantEntity/utils/summary.tsx
> +                  );
Utilise les styles standard de antd qui prend en charge automatiquement les variables du themes. Comme partout ailleurs. pas de custom class. En plus les tag on l'air visuellement off par rapport au reste.

2023-10-27 10:14 UTC, atoulous commented on src/views/VariantEntity/utils/summary.tsx
> +                  );
Ok je change pour `<Tag color={getTagColor(value)}`

2023-10-27 15:39 UTC, francisl approved these changes

2023-10-27 16:52 UTC, kstonge approved these changes

2023-10-28 10:10 UTC, merged