feat: CQDG-617 add tooltip on disable buttons on data explo
Ferlab-Ste-Justine/cqdg-portal-ui pull request #254
Opened 2024-02-28 20:20 UTC by atoulous

# feat: CQDG-617 add tooltip on disable buttons on data explo

- closes #TICKET_NUMBER

## Description

https://ferlab-crsj.atlassian.net/browse/CQDG-617

Acceptance Criterias

## Validation

- [ ] Code Approved
- [ ] QA Done
- [ ] Design/UI Approved from design

## Screenshot
<img width="951" alt="image" src="https://github.com/Ferlab-Ste-Justine/cqdg-portal-ui/assets/15524246/54e44c3f-9040-4508-b82b-319e22c5317f">

2024-03-04 15:04 UTC, AltefrohneGaelle commented on src/components/reports/DownloadClinicalDataDropdown.tsx
> +      {/** need a empty div below to show tooltip when Dropdown is disabled */}
Est ce que tu as testé pour ça, juste une idée comme ça, sans la `div` mais avec le css pour gérer les tooltips safari?
`&:before {
    content: '';
    display: block;
}`

2024-03-04 15:04 UTC, AltefrohneGaelle commented on src/locales/fr.ts
> +      selectAllResults: 'Sélectionner tous les résultats',
Ça ne devrait pas être de l'impératif ? Sélectionnez comme ta clé plus bas youMustSelect ?

2024-03-04 16:21 UTC, atoulous commented on src/components/reports/DownloadClinicalDataDropdown.tsx
> +      {/** need a empty div below to show tooltip when Dropdown is disabled */}
C'est pas le meme probleme du tout, le Tooltip au dessus du Dropdown a besoin d'un espace selectionnable qui n'existe pas si le Dropdown est disabled. Va savoir pourquoi ca fonctionne sur le Button disable par contre.
Jviens de tester au cas ou mais non ca marche pas.

2024-03-04 16:25 UTC, atoulous commented on src/locales/fr.ts
> +      selectAllResults: 'Sélectionner tous les résultats',
Non c'est pas mal tout en 'er' sur le portail.
Je vais passer le youMustSelect en 'er'

2024-03-04 17:58 UTC, AltefrohneGaelle approved these changes

2024-03-04 18:15 UTC, ethienneroy requested changes

2024-03-04 18:15 UTC, ethienneroy commented on src/locales/fr.ts
> +      selectAllResults: 'Sélectionner tous les résultats',
`On garde comme ca je veux pas perdre du temps la dessus` 
Ca va sortir en QA, création de ticket et quelqu'un devra perdre du temps dessus. Assurons-nous que ce soit la bonne chose déjà, vu que c'est déjà remonter :)

2024-03-04 18:48 UTC, atoulous commented on src/locales/fr.ts
> +      selectAllResults: 'Sélectionner tous les résultats',
Ces modif ici, j'ai juste fix les `e` en `é`. Ca ne changera pas.
Le nouveau field youMustSelect correspond a l'analyse sur le ticket.
Il y a rien de plus a faire pour le moment.

2024-03-04 18:51 UTC, atoulous commented on src/locales/fr.ts
> +      selectAllResults: 'Sélectionner tous les résultats',
Il y a les 2 sur l'app en fonction du besoin. Ce ticket n'est pas la pour remettre en question tout ca.
<img width="440" alt="image" src="https://github.com/Ferlab-Ste-Justine/cqdg-portal-ui/assets/15524246/d2287d11-d6a1-42d9-8a78-690e468964b3">

2024-03-05 19:36 UTC, ethienneroy commented on src/locales/fr.ts
> +      selectAllResults: 'Sélectionner tous les résultats',
@kstonge quel est ton avis ici par rapport à ca? 
nouveau ticket ou fixer maintenant ? :)

2024-03-06 18:14 UTC, kstonge commented on src/locales/fr.ts
> +      selectAllResults: 'Sélectionner tous les résultats',
Il y a bel et bien un mélange de `er` et de `ez`. Étant donné que le ticket mentionne `ez`, on va l'accepter tel quel.

2024-03-06 20:00 UTC, ethienneroy approved these changes

2024-03-07 17:36 UTC, kstonge approved these changes

2024-03-07 19:12 UTC, merged