feat: CQDG-723 add getDocLang on each doc link
Ferlab-Ste-Justine/cqdg-portal-ui pull request #296
Opened 2024-07-03 21:28 UTC by atoulous

# FIX | FEAT | REFACTOR | PERF | DOCS : TITLE

- closes #TICKET_NUMBER

## Description

[JIRA LINK]

Acceptance Criterias

## Validation

- [ ] Code Approved
- [ ] QA Done
- [ ] Design/UI Approved from design

## Screenshot

2024-07-04 11:56 UTC, adipaul1981 approved these changes

2024-07-04 19:46 UTC, francisl requested changes
src/utils/index.ts ca mérite un nom un peu plus clair que ca

2024-07-04 19:46 UTC, francisl commented on src/utils/index.ts
> +import getStoreConfig from '../store';
absolute path!

2024-07-05 20:18 UTC, francisl approved these changes
:shipit:

2024-07-08 13:47 UTC, merged