Cqdg 18 refactor participant donor index
Ferlab-Ste-Justine/cqdg-portal-ui pull request #3
Opened 2022-07-19 15:36 UTC by atoulous

2022-07-20 15:44 UTC, francisl requested changes

2022-07-20 15:44 UTC, francisl commented on src/graphql/studies/models.ts
> +import { IParticipantEntity } from '../participants/models';
no relative import

2022-07-20 15:44 UTC, francisl commented on src/store/fenceCavatica/thunks.tsx
> +  // });
delete

2022-07-20 15:44 UTC, francisl commented on src/store/index.tsx
> +    return defaultMid;
pas nécessaire de faire d'assignation

2022-07-20 15:44 UTC, francisl commented on src/utils/dataFiles.ts
> +    // intersection(userAcls, file.acl).length > 0 ||
supprimer les commentaires

2022-07-20 15:44 UTC, francisl commented on src/views/DataExploration/index.tsx
> +          // eslint-disable-next-line react/jsx-key
besoin de justification pour la déactivation de règles

2022-07-20 15:44 UTC, francisl commented on src/views/DataExploration/index.tsx
> +  // const biospecimenMappingResults = useGetExtendedMappings(INDEXES.BIOSPECIMEN);
delete

2022-07-20 15:44 UTC, francisl commented on src/views/DataExploration/index.tsx
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
?

2022-07-20 15:44 UTC, francisl commented on src/graphql/files/actions.ts
> +  if (process.env.NODE_ENV === 'development' && error) {
si on est pour faire ce type de log, il fautdrait faire un logger au lieu d'un paquet de if.

genre `logger(error)` ou `error && logger(error)` si on veux eviter un func call.

2022-07-20 15:44 UTC, francisl commented on src/graphql/files/actions.ts
> +  // @ts-ignore
no ignore sans justification

2022-07-20 15:44 UTC, francisl commented on src/graphql/participants/actions.ts
> +  }
si on est pour faire ce type de log, il fautdrait faire un logger au lieu d'un paquet de if.

genre `logger(error)` ou `error && logger(error)` si on veux eviter un func call.

2022-07-20 15:44 UTC, francisl commented on src/views/DataExploration/index.tsx
> +          // eslint-disable-next-line react/jsx-key
pas déactivation sans justification détaillée

2022-07-20 17:36 UTC, atoulous commented on src/store/fenceCavatica/thunks.tsx
> +  // });
@francisl `startBulkImportJob` viens de include, je la supprime ici ou il faut l'adapter pour cqdg ? je ne sais pas a quoi ca sert

2022-07-20 17:38 UTC, atoulous commented on src/store/index.tsx
> +    return defaultMid;
c'etait plus pour moi je need pas les log redux, mais je vais le definir avec une variable d'env c'est plus clean

2022-07-20 17:39 UTC, atoulous commented on src/utils/dataFiles.ts
> +    // intersection(userAcls, file.acl).length > 0 ||
ici je ne savais pas ce que c'etait `acl` pour un File, puis si c'etait important

2022-07-20 17:53 UTC, atoulous commented on src/graphql/files/actions.ts
> +  if (process.env.NODE_ENV === 'development' && error) {
on peut faire un logger effectivement, en attendant j'avais besoin de l'erreur graphql en dev. Il y a deja des console.warn ou .error present. Le tout serai a cleaner sur un autre ticket

2022-07-20 18:40 UTC, francisl commented on src/store/fenceCavatica/thunks.tsx
> +  // });
si c'est pas utile, on delete.

2022-07-20 19:22 UTC, francisl requested changes
le fichier eslint dans nos autres projet est `.eslintrc.json`

2022-07-20 19:22 UTC, francisl commented on src/utils/dataFiles.ts
> +    // intersection(userAcls, file.acl).length > 0 ||
juste effacé, si c'est utile, on va le réajouter

2022-07-20 19:22 UTC, francisl commented on src/graphql/files/actions.ts
> +  if (process.env.NODE_ENV === 'development' && error) {
ca ajoute plus de dette technique. fait un logger juste pour ton code, ca va pas être trop long. on fixera le legacy dans un autre ticket

2022-07-20 19:22 UTC, francisl commented on src/graphql/participants/actions.ts
> +  }
point up

2022-07-20 19:38 UTC, atoulous commented
> le fichier eslint dans nos autres projet est `.eslintrc.json`

c'etait .eslint.json avant que je ne rename donc ca marchait pas. .eslintrc ou .eslintrc.json c'est la meme chose le .json ne sert a rien donc j'avais rename .eslintrc

2022-07-21 15:43 UTC, francisl approved these changes

2022-07-21 15:43 UTC, francisl commented on src/store/savedSet/index.ts
> +import EnvironmentVariables from '../../helpers/EnvVariables';
absolute import

2022-07-21 15:44 UTC, merged